# Generated by Django 5.2.8 on 2025-11-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('hotel_owner', 'Hotel Owner'), ('cars_admin', 'Car Rental Owner'), ('airline_company', 'Airline Admin'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
