# Generated by Django 5.2.8 on 2025-12-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owners',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hotel', 'Hotel Owner'), ('car', 'Car Owner'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
