# Generated by Django 5.2.8 on 2025-12-04 19:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_owners_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='owners',
            name='role',
            field=models.CharField(choices=[('hotel', 'Hotel Owner'), ('car', 'Car Owner')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
