# Generated by Django 5.2.8 on 2025-12-13 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('twin', 'Twin Room'), ('deluxe', 'Deluxe Room'), ('family', 'Family Room')], max_length=20)),
                ('name', models.CharField(help_text='e.g., Deluxe Ocean View', max_length=100)),
                ('description', models.TextField()),
                ('max_guests', models.IntegerField()),
                ('bed_type', models.CharField(choices=[('single', 'Single Bed'), ('double', 'Double Bed'), ('king', 'King Bed'), ('twin', 'Twin Beds')], max_length=20)),
                ('number_of_beds', models.IntegerField(default=1)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_rooms', models.IntegerField(default=1)),
                ('facilities', models.TextField(blank=True, help_text='Comma-separated (AC, TV, Balcony, etc.)')),
                ('is_available', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotelsmodel')),
            ],
            options={
                'ordering': ['price_per_night'],
            },
        ),
    ]
